# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.0'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.1', '>= 7.1.3'

# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.5'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '~> 6.0'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem 'jbuilder'

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Migration
gem 'annotate'
gem 'ridgepole'

# enum-help
gem 'enum_help'

# config
gem 'config'
gem 'seed-fu'

# searcher and sorter
gem 'kaminari'
gem 'ransack', github: 'activerecord-hackery/ransack'

# sendgrid mail
gem 'sendgrid-ruby'

# devise
gem 'devise'

gem 'activerecord-import'

gem 'rack-cors'

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'pry-rails'

  # Detect N+1
  gem 'bullet'

  # Seeding
  # Code analyzer
  gem 'rubocop'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
  # Erb analyzer
  gem 'erb_lint'

  # SAST
  gem 'brakeman'
end

group :development do
  gem 'letter_opener'
  gem 'letter_opener_web'
end

group :test do
  gem 'factory_bot_rails', '= 6.2.0'
  gem 'rails-controller-testing'
  gem 'rspec-rails'
  gem 'simplecov'
  gem 'simplecov-console'
  gem 'webmock'
end

group :production do
  # rubocop:disable Bundler/OrderedGems
  gem 'stackprof'
  gem 'sentry-rails'
  gem 'sentry-ruby'
  # rubocop:enable Bundler/OrderedGems
end
